Fix crowdin file
vtex-apps/cookiebot pull request #11
Opened 2021-08-20 10:01 UTC by daniserejo

#### What problem is this solving?

Fix crowdin file to ensure correct files on crowdin integration

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [✔️] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

#### Type of changes

✔️ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements

2021-08-24 13:36 UTC, camilavcoutinho requested changes

2021-08-24 13:36 UTC, camilavcoutinho commented on CHANGELOG.md
> +- Fix crowdin.yml file
```suggestion
- Crowdin configuration file
```

2021-08-24 16:37 UTC, camilavcoutinho approved these changes

2021-09-08 13:08 UTC, igorbrasileiro approved these changes
Remove changelog changes and merge.

2021-09-08 13:08 UTC, igorbrasileiro commented on CHANGELOG.md
> +
```suggestion
```

2021-09-08 16:34 UTC, merged