New metadata for publishing on App Store
vtex-apps/cookiebot pull request #7
Opened 2020-08-20 19:45 UTC by manoel-gumes

What problem is this solving?

Estrutura de pastas (public/metadata) para o novo formato aceito pela App Store.
-> Nesta fase de transição, teremos as duas estruturas de pastas coexistindo.

Adição do arquivo crowdin.yml para localização.

How should this be manually tested?

As mudificações não alteram o comportamento do App.

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-08-21 00:31 UTC, marlonguimaraes approved these changes

2020-09-15 17:08 UTC, klzns requested changes

2020-09-15 17:08 UTC, klzns commented on crowdin.yml
> +    source: "/cookiebot/public/metadata/messages/pt-BR.json"
I think this cookiebot path have to be removed

2020-09-15 19:51 UTC, klzns approved these changes

2020-09-15 19:51 UTC, klzns requested changes
Needs rebase

2020-09-15 19:51 UTC, klzns commented on CHANGELOG.md
> +- New metadata for publishing on App Store
```suggestion
### Added
- New metadata for publishing on App Store
```

2020-09-15 20:53 UTC, klzns approved these changes

2020-09-15 21:04 UTC, merged